DROP TABLE IF EXISTS shop;
DROP TABLE IF EXISTS people;
DROP TABLE IF EXISTS user;

CREATE TABLE shop (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  category TEXT NOT NULL,
  address TEXT NOT NULL,
  latitude REAL NOT NULL,
  longitude REAL NOT NULL,
  storespace INTEGER NOT NULL,
  maxcapacity INTEGER NOT NULL,
);

CREATE TABLE people (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  shopid INTEGER NOT NULL,
  number INTEGER NOT NULL,
  capacity REAL NOT NULL,
  waitingtime INTEGER NOT NULL,
  lastupdate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (shopid) REFERENCES shop (id)
);

CREATE TABLE user (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  shopaddress TEXT NOT NULL,
  login TEXT NOT NULL,
  password TEXT NOT NULL,
  FOREIGN KEY (shopaddress) REFERENCES shop (address)
);